import {DISCIPLINES,TOOL_LABELS,UNIVERSAL_CONSTANTS,SOLVENTS,QUOTES,disciplineFromLabel} from './config.js';
import {all,put,get,remove,uid,migrateLegacy,exportAll,importAll,requestPersistence,estimateStorage} from './storage.js';
import {renderTool,downloadText} from './tools.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let activeDiscipline='biochem', activeExperimentId=null;
let cache={experiments:[],protocols:[],syntheses:[],discussions:[],calculations:[],tasks:[]};
const stores=Object.keys(cache);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const toast=(text)=>{const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};

async function refresh(){for(const s of stores)cache[s]=(await all(s)).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));renderAll();}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent=id==='today'?'Good day, scientist.':id==='workspace'?DISCIPLINES[activeDiscipline].label:id.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());window.scrollTo({top:0,behavior:'smooth'});}
function renderAll(){renderTasks();renderExperiments();renderProtocols();renderSyntheses();renderDiscussions();renderSearch();renderStats();renderReferences();}
function setupNav(){$$('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('[data-jump]').forEach(n=>n.onclick=()=>showView(n.dataset.jump));}

function renderStats(){const cards=[['Experiments',cache.experiments.length],['Protocols',cache.protocols.length],['Syntheses',cache.syntheses.length],['Attached calculations',cache.calculations.filter(c=>c.experimentId).length]];$('#stats').innerHTML=cards.map(([k,v])=>`<article><span>${esc(k)}</span><b>${v}</b></article>`).join('');$('#recentExperiments').innerHTML=cache.experiments.length?cache.experiments.slice(0,4).map(e=>`<button class="recent-row" data-open-exp="${e.id}"><span><b>${esc(e.title)}</b><small>${esc(e.discipline)} · ${esc(e.type)}</small></span><i>Open →</i></button>`).join(''):'<div class="empty-state">No experiments yet. Start with the question you want to answer.</div>';$$('[data-open-exp]').forEach(b=>b.onclick=()=>openExperimentBench(b.dataset.openExp));}

async function renderTasks(){$('#taskCount').textContent=cache.tasks.filter(t=>!t.done).length;$('#taskList').innerHTML=cache.tasks.map(t=>`<li class="${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-task-check="${t.id}"><span>${esc(t.text)}</span><button data-task-del="${t.id}">×</button></li>`).join('');$$('[data-task-check]').forEach(x=>x.onchange=async()=>{const t=await get('tasks',x.dataset.taskCheck);t.done=x.checked;t.updatedAt=new Date().toISOString();await put('tasks',t);await refresh()});$$('[data-task-del]').forEach(x=>x.onclick=async()=>{await remove('tasks',x.dataset.taskDel);await refresh()});}

function renderExperiments(){const q=($('#experimentFilter')?.value||'').toLowerCase();const list=cache.experiments.filter(e=>[e.title,e.project,e.discipline,e.type,e.objective,e.observation,e.interpretation].join(' ').toLowerCase().includes(q));$('#experimentList').innerHTML=list.length?list.map(e=>{const calcN=cache.calculations.filter(c=>c.experimentId===e.id).length;return `<article class="record-card"><div class="record-top"><div><span class="tag">${esc(e.discipline)} · ${esc(e.type)}</span><h3>${esc(e.title)}</h3><small>${esc(e.project||'No project')} · ${fmtDate(e.createdAt)}</small></div><div class="record-actions"><button data-bench-exp="${e.id}">Bench</button><button data-edit-exp="${e.id}">Edit</button><button class="danger" data-del-exp="${e.id}">Delete</button></div></div><p><b>Objective</b>${esc(e.objective||'—')}</p><div class="record-split"><p><b>Observation</b>${esc(e.observation||'—')}</p><p><b>Interpretation</b>${esc(e.interpretation||'—')}</p></div><footer><span>${calcN} attached calculation${calcN===1?'':'s'}</span><span>${esc(e.nextStep||'')}</span></footer></article>`}).join(''):'<div class="placeholder">No matching experiments.</div>';$$('[data-bench-exp]').forEach(b=>b.onclick=()=>openExperimentBench(b.dataset.benchExp));$$('[data-edit-exp]').forEach(b=>b.onclick=()=>openExperimentDialog(b.dataset.editExp));$$('[data-del-exp]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this experiment? Attached calculations will remain as historical records.')){await remove('experiments',b.dataset.delExp);await refresh()}});}
async function openExperimentBench(id){const e=await get('experiments',id);if(!e)return;activeExperimentId=id;activeDiscipline=disciplineFromLabel(e.discipline).id;openBench(activeDiscipline,id);}

function openBench(id,experimentId=null){activeDiscipline=id;activeExperimentId=experimentId;const d=DISCIPLINES[id];$('#workspaceTitle').textContent=d.label;$('#workspaceBlurb').textContent=d.blurb;$('#contextChip').textContent=experimentId?`Experiment: ${cache.experiments.find(e=>e.id===experimentId)?.title||'record'}`:'Discipline workspace';$('#templateStrip').innerHTML=d.templates.map(t=>`<button data-template="${esc(t)}"><b>${esc(t)}</b><span>Start record →</span></button>`).join('');$('#toolGrid').innerHTML=d.tools.map(t=>`<button data-tool="${t}"><span>↗</span><b>${esc(TOOL_LABELS[t])}</b></button>`).join('');$('#disciplineRefs').innerHTML=d.references.map(([a,b])=>`<div><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('');const recent=cache.experiments.filter(e=>disciplineFromLabel(e.discipline).id===id).slice(0,4);$('#benchRecent').innerHTML=recent.length?recent.map(e=>`<button data-bench-exp="${e.id}"><b>${esc(e.title)}</b><span>${esc(e.type)}</span></button>`).join(''):'<div class="empty-state">No records on this bench yet.</div>';$$('[data-template]').forEach(x=>x.onclick=()=>openExperimentDialog(null,d.label,x.dataset.template));$$('[data-tool]').forEach(x=>x.onclick=()=>renderTool($('#toolPanel'),x.dataset.tool));$$('#benchRecent [data-bench-exp]').forEach(x=>x.onclick=()=>openExperimentBench(x.dataset.benchExp));$('#toolPanel').classList.add('hidden');showView('workspace');}

function typesFor(label){const d=disciplineFromLabel(label);return d.templates;}
async function openExperimentDialog(id=null,discipline=null,type=null){const e=id?await get('experiments',id):null;$('#expId').value=e?.id||'';$('#expTitle').value=e?.title||'';$('#expProject').value=e?.project||'';$('#expDiscipline').value=e?.discipline||discipline||DISCIPLINES[activeDiscipline].label;fillTypes(e?.type||type);$('#expObjective').value=e?.objective||'';$('#expMaterials').value=e?.materials||'';$('#expProcedure').value=e?.procedure||'';$('#expObservation').value=e?.observation||'';$('#expInterpretation').value=e?.interpretation||'';$('#expNext').value=e?.nextStep||'';$('#experimentDialog').showModal();}
function fillTypes(selected){const label=$('#expDiscipline').value;$('#expType').innerHTML=typesFor(label).map(t=>`<option ${t===selected?'selected':''}>${esc(t)}</option>`).join('');}
async function saveExperiment(ev){ev.preventDefault();const id=$('#expId').value||uid('exp');const existing=await get('experiments',id);const now=new Date().toISOString();await put('experiments',{id,title:$('#expTitle').value.trim(),project:$('#expProject').value.trim(),discipline:$('#expDiscipline').value,type:$('#expType').value,objective:$('#expObjective').value.trim(),materials:$('#expMaterials').value.trim(),procedure:$('#expProcedure').value.trim(),observation:$('#expObservation').value.trim(),interpretation:$('#expInterpretation').value.trim(),nextStep:$('#expNext').value.trim(),createdAt:existing?.createdAt||now,updatedAt:now});$('#experimentDialog').close();await refresh();showView('experiments');toast('Experiment saved locally');}

function renderProtocols(){const list=cache.protocols;$('#protocolList').innerHTML=list.length?list.map(p=>`<article class="record-card"><div class="record-top"><div><span class="tag">${esc(p.discipline)} · v${p.version}</span><h3>${esc(p.title)}</h3><small>${fmtDate(p.updatedAt)}</small></div><div class="record-actions"><button data-version-protocol="${p.id}">New version</button><button data-edit-protocol="${p.id}">Edit</button><button class="danger" data-del-protocol="${p.id}">Delete</button></div></div><p><b>Purpose</b>${esc(p.purpose||'—')}</p><details><summary>Method & optimization</summary><div class="details-grid"><p><b>Materials</b>${esc(p.materials||'—')}</p><p><b>Steps</b>${esc(p.steps||'—')}</p><p><b>Critical parameters</b>${esc(p.critical||'—')}</p><p><b>Troubleshooting</b>${esc(p.troubleshooting||'—')}</p><p><b>Safety</b>${esc(p.safety||'—')}</p><p><b>Optimization notes</b>${esc(p.optimization||'—')}</p></div></details></article>`).join(''):'<div class="placeholder">No protocols yet.</div>';$$('[data-edit-protocol]').forEach(b=>b.onclick=()=>openProtocolDialog(b.dataset.editProtocol));$$('[data-version-protocol]').forEach(b=>b.onclick=()=>openProtocolDialog(b.dataset.versionProtocol,true));$$('[data-del-protocol]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this protocol version?')){await remove('protocols',b.dataset.delProtocol);await refresh()}});}
async function openProtocolDialog(id=null,newVersion=false){const p=id?await get('protocols',id):null;$('#protocolId').value=newVersion?'':p?.id||'';$('#protocolFamily').value=p?.familyId||uid('pfam');$('#protocolVersion').value=newVersion?(Number(p?.version||0)+1):(p?.version||1);$('#protocolTitle').value=p?.title||'';$('#protocolDiscipline').value=p?.discipline||DISCIPLINES[activeDiscipline].label;for(const k of ['Purpose','Materials','Steps','Critical','Troubleshooting','Safety','Optimization'])$('#protocol'+k).value=p?.[k.toLowerCase()]||'';$('#protocolDialog').showModal();}
async function saveProtocol(ev){ev.preventDefault();const id=$('#protocolId').value||uid('pro');const existing=await get('protocols',id);const now=new Date().toISOString();await put('protocols',{id,familyId:$('#protocolFamily').value,title:$('#protocolTitle').value.trim(),discipline:$('#protocolDiscipline').value,version:Number($('#protocolVersion').value)||1,purpose:$('#protocolPurpose').value.trim(),materials:$('#protocolMaterials').value.trim(),steps:$('#protocolSteps').value.trim(),critical:$('#protocolCritical').value.trim(),troubleshooting:$('#protocolTroubleshooting').value.trim(),safety:$('#protocolSafety').value.trim(),optimization:$('#protocolOptimization').value.trim(),createdAt:existing?.createdAt||now,updatedAt:now});$('#protocolDialog').close();await refresh();toast('Protocol version saved');}

function renderSyntheses(){const list=cache.syntheses;$('#synthesisList').innerHTML=list.length?list.map(s=>`<article class="record-card"><div class="record-top"><div><span class="tag">${esc(s.discipline||'Organic Chemistry')}</span><h3>${esc(s.title)}</h3><small>${fmtDate(s.updatedAt)}</small></div><div class="record-actions"><button data-copy-smiles="${s.id}">Copy SMILES</button>${s.molblock?`<button data-export-mol="${s.id}">Export MOL</button>`:''}<button data-edit-syn="${s.id}">Edit</button><button class="danger" data-del-syn="${s.id}">Delete</button></div></div><div class="structure-strip"><code>${esc(s.smiles||'No SMILES')}</code><small>${esc(s.inchi||'')}</small></div><div class="details-grid"><p><b>Reagents / equivalents</b>${esc(s.reagents||'—')}</p><p><b>Conditions</b>${esc(s.conditions||'—')}</p><p><b>Workup</b>${esc(s.workup||'—')}</p><p><b>Purification</b>${esc(s.purification||'—')}</p><p><b>Yield</b>${esc(s.yield||'—')}</p><p><b>Characterization</b>${esc(s.characterization||'—')}</p></div></article>`).join(''):'<div class="placeholder">No synthesis records yet.</div>';$$('[data-edit-syn]').forEach(b=>b.onclick=()=>openSynthesisDialog(b.dataset.editSyn));$$('[data-del-syn]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this synthesis record?')){await remove('syntheses',b.dataset.delSyn);await refresh()}});$$('[data-copy-smiles]').forEach(b=>b.onclick=async()=>{const s=await get('syntheses',b.dataset.copySmiles);await navigator.clipboard.writeText(s?.smiles||'');toast('SMILES copied')});$$('[data-export-mol]').forEach(b=>b.onclick=async()=>{const s=await get('syntheses',b.dataset.exportMol);downloadText(`${safeName(s.title)}.mol`,s.molblock,'chemical/x-mdl-molfile')});}
async function openSynthesisDialog(id=null){const s=id?await get('syntheses',id):null;$('#synId').value=s?.id||'';for(const [el,key] of [['synTitle','title'],['synProject','project'],['synSmiles','smiles'],['synInchi','inchi'],['synMol','molblock'],['synReagents','reagents'],['synConditions','conditions'],['synWorkup','workup'],['synPurification','purification'],['synYield','yield'],['synCharacterization','characterization'],['synObservation','observation']])$('#'+el).value=s?.[key]||'';$('#synthesisDialog').showModal();}
async function saveSynthesis(ev){ev.preventDefault();const id=$('#synId').value||uid('syn'),existing=await get('syntheses',id),now=new Date().toISOString();await put('syntheses',{id,title:$('#synTitle').value.trim(),project:$('#synProject').value.trim(),discipline:'Organic Chemistry',smiles:$('#synSmiles').value.trim(),inchi:$('#synInchi').value.trim(),molblock:$('#synMol').value,reagents:$('#synReagents').value.trim(),conditions:$('#synConditions').value.trim(),workup:$('#synWorkup').value.trim(),purification:$('#synPurification').value.trim(),yield:$('#synYield').value.trim(),characterization:$('#synCharacterization').value.trim(),observation:$('#synObservation').value.trim(),createdAt:existing?.createdAt||now,updatedAt:now});$('#synthesisDialog').close();await refresh();toast('Synthesis record saved');}
function safeName(s){return String(s||'record').replace(/[^a-z0-9_-]+/gi,'_').slice(0,70)}

function renderDiscussions(){const list=cache.discussions;$('#discussionList').innerHTML=list.length?list.map(d=>`<article class="record-card"><div class="record-top"><div><span class="tag">${esc(d.project||'PROJECT')}</span><h3>${esc(d.title)}</h3><small>${fmtDate(d.updatedAt)}</small></div><div class="record-actions"><button data-edit-disc="${d.id}">Edit</button><button class="danger" data-del-disc="${d.id}">Delete</button></div></div><div class="details-grid"><p><b>Finding / question</b>${esc(d.finding||'—')}</p><p><b>Evidence</b>${esc(d.evidence||'—')}</p><p><b>Interpretation</b>${esc(d.interpretation||'—')}</p><p><b>Limitations</b>${esc(d.limitations||'—')}</p><p><b>Next experiment</b>${esc(d.nextExperiment||'—')}</p></div></article>`).join(''):'<div class="placeholder">No project discussion notes yet.</div>';$$('[data-edit-disc]').forEach(b=>b.onclick=()=>openDiscussionDialog(b.dataset.editDisc));$$('[data-del-disc]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this discussion note?')){await remove('discussions',b.dataset.delDisc);await refresh()}});}
async function openDiscussionDialog(id=null){const d=id?await get('discussions',id):null;$('#discId').value=d?.id||'';for(const [el,key] of [['discTitle','title'],['discProject','project'],['discFinding','finding'],['discEvidence','evidence'],['discInterpretation','interpretation'],['discLimitations','limitations'],['discNext','nextExperiment']])$('#'+el).value=d?.[key]||'';$('#discussionDialog').showModal();}
async function saveDiscussion(ev){ev.preventDefault();const id=$('#discId').value||uid('disc'),existing=await get('discussions',id),now=new Date().toISOString();await put('discussions',{id,title:$('#discTitle').value.trim(),project:$('#discProject').value.trim(),finding:$('#discFinding').value.trim(),evidence:$('#discEvidence').value.trim(),interpretation:$('#discInterpretation').value.trim(),limitations:$('#discLimitations').value.trim(),nextExperiment:$('#discNext').value.trim(),createdAt:existing?.createdAt||now,updatedAt:now});$('#discussionDialog').close();await refresh();toast('Discussion note saved');}

function renderSearch(){const q=($('#globalSearch')?.value||'').trim().toLowerCase();if(!q){$('#searchResults').innerHTML='<div class="placeholder">Search titles, projects, methods, observations, interpretations, structures, or protocol text.</div>';return}const result=[];for(const [store,items] of Object.entries(cache)){for(const item of items){const blob=JSON.stringify(item).toLowerCase();if(blob.includes(q))result.push({store,item})}}$('#searchResults').innerHTML=result.length?result.slice(0,100).map(({store,item})=>`<article class="search-hit"><span class="tag">${store}</span><b>${esc(item.title||item.text||item.toolId||'Record')}</b><small>${esc(item.project||item.discipline||'')} · ${fmtDate(item.updatedAt||item.createdAt)}</small></article>`).join(''):'<div class="placeholder">No matches.</div>';}

function renderReferences(){const sel=$('#referenceDiscipline');if(!sel)return;if(!sel.options.length)sel.innerHTML=Object.values(DISCIPLINES).map(d=>`<option value="${d.id}">${esc(d.label)}</option>`).join('');const id=sel.value||activeDiscipline,d=DISCIPLINES[id];$('#universalConstants').innerHTML=UNIVERSAL_CONSTANTS.map(([a,b])=>`<article><span>${esc(a)}</span><b>${esc(b)}</b></article>`).join('');$('#contextReferences').innerHTML=d.references.map(([a,b])=>`<article><span>${esc(a)}</span><b>${esc(b)}</b></article>`).join('');$('#solventReference').innerHTML=id==='orgo'?`<div class="table-wrap"><table><thead><tr><th>Solvent</th><th>Formula</th><th>MW</th><th>bp °C</th><th>Density</th><th>Vacuum @ 40 °C</th></tr></thead><tbody>${SOLVENTS.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.formula)}</td><td>${s.mw}</td><td>${s.bp}</td><td>${s.density}</td><td>${s.vacuum40} mbar</td></tr>`).join('')}</tbody></table><p class="reference-note">Rotavap vacuum values are BÜCHI solvent-table reference values for a 40 °C boiling point. Instrument manual and SDS take priority.</p></div>`:'';}

async function attachCalculation(detail){const now=new Date().toISOString();const snap={...structuredClone(detail),id:uid('calc'),experimentId:activeExperimentId||null,discipline:DISCIPLINES[activeDiscipline].label,createdAt:now,updatedAt:now};await put('calculations',snap);await refresh();toast(activeExperimentId?'Calculation attached to experiment':'Calculation saved to local history');}

async function doExport(){const data=await exportAll();downloadText(`noor-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2),'application/json');toast('Backup exported');}
async function importBackup(file){const text=await file.text();const payload=JSON.parse(text);await importAll(payload,{replace:false});await refresh();toast('Backup imported');}
function exportExperimentsCsv(){const cols=['title','project','discipline','type','objective','materials','procedure','observation','interpretation','nextStep','createdAt','updatedAt'];const quote=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=cols.join(',')+'\n'+cache.experiments.map(e=>cols.map(c=>quote(e[c])).join(',')).join('\n');downloadText('noor-experiments.csv',csv,'text/csv');}
async function updateStorageStatus(){const est=await estimateStorage();$('#storageStatus').textContent=est?`${(est.usage/1048576).toFixed(1)} MB used locally · ${(est.quota/1048576).toFixed(0)} MB available quota`:'Browser storage estimate unavailable';}

function bind(){setupNav();$$('.discipline').forEach(b=>b.onclick=()=>openBench(b.dataset.discipline));$('#taskForm').onsubmit=async e=>{e.preventDefault();const text=$('#taskInput').value.trim();if(!text)return;const now=new Date().toISOString();await put('tasks',{id:uid('task'),text,done:false,createdAt:now,updatedAt:now});$('#taskInput').value='';await refresh()};$('#newExperiment').onclick=()=>openExperimentDialog();$('#workspaceNew').onclick=()=>openExperimentDialog(null,DISCIPLINES[activeDiscipline].label);$('#newProtocol').onclick=()=>openProtocolDialog();$('#newSynthesis').onclick=()=>openSynthesisDialog();$('#newDiscussion').onclick=()=>openDiscussionDialog();$('#experimentForm').onsubmit=saveExperiment;$('#protocolForm').onsubmit=saveProtocol;$('#synthesisForm').onsubmit=saveSynthesis;$('#discussionForm').onsubmit=saveDiscussion;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#expDiscipline').onchange=()=>fillTypes();$('#experimentFilter').oninput=renderExperiments;$('#globalSearch').oninput=renderSearch;$('#referenceDiscipline').onchange=renderReferences;$('#exportBackup').onclick=doExport;$('#exportCsv').onclick=exportExperimentsCsv;$('#importBackup').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]).catch(err=>alert(err.message));$('#persistStorage').onclick=async()=>toast((await requestPersistence())?'Browser granted persistent storage':'Persistent storage was not granted; backups remain important');$('#molFile').onchange=async e=>{const f=e.target.files[0];if(f)$('#synMol').value=await f.text()};document.addEventListener('noor-attach-calculation',e=>attachCalculation(e.detail));document.addEventListener('online',updateNetwork);document.addEventListener('offline',updateNetwork);}
function updateNetwork(){$('#offlineText').textContent=navigator.onLine?'Local-first · online':'Offline · records & calculators available';}
async function init(){await migrateLegacy();bind();const now=new Date();$('#dateLabel').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const quote=QUOTES[now.getDate()%QUOTES.length];$('#quoteText').textContent=quote.text;$('#quoteAuthor').textContent=`— ${quote.author} · ${quote.source}`;await refresh();updateNetwork();updateStorageStatus();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});}
init().catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend',`<div class="fatal">NOOR could not start: ${esc(e.message)}</div>`)});
