const DB_NAME='noor-eln';const DB_VERSION=1;const STORES=['experiments','protocols','syntheses','discussions','plates','calculations','tasks','timers','settings'];
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;for(const s of STORES)if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function tx(store,mode='readonly'){const db=await openDB();return db.transaction(store,mode).objectStore(store)}
export async function put(store,value){const os=await tx(store,'readwrite');return new Promise((resolve,reject)=>{const r=os.put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error);});}
export async function get(store,id){const os=await tx(store);return new Promise((resolve,reject)=>{const r=os.get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function all(store){const os=await tx(store);return new Promise((resolve,reject)=>{const r=os.getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});}
export async function remove(store,id){const os=await tx(store,'readwrite');return new Promise((resolve,reject)=>{const r=os.delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
export async function clearStore(store){const os=await tx(store,'readwrite');return new Promise((resolve,reject)=>{const r=os.clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
export function uid(prefix='rec'){return `${prefix}_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`}
export async function migrateLegacy(){for(const [key,store] of [['noor.experiments','experiments'],['noor.tasks','tasks']]){try{const raw=localStorage.getItem(key);if(!raw)continue;const arr=JSON.parse(raw);if(Array.isArray(arr)){for(const item of arr){if(!item.id)item.id=uid(store.slice(0,3));await put(store,item);}localStorage.removeItem(key);}}catch{}}}
export async function exportAll(){const payload={schema:'noor-backup',version:1,exportedAt:new Date().toISOString(),stores:{}};for(const s of STORES)payload.stores[s]=await all(s);return payload;}
export async function importAll(payload,{replace=false}={}){if(!payload||payload.schema!=='noor-backup'||!payload.stores)throw new Error('This is not a valid NOOR backup.');for(const s of STORES){if(replace)await clearStore(s);for(const item of payload.stores[s]||[])await put(s,item);}return true;}
export async function requestPersistence(){if(!navigator.storage?.persist)return false;return navigator.storage.persist();}
export async function estimateStorage(){if(!navigator.storage?.estimate)return null;return navigator.storage.estimate();}
