import {SOLVENTS,TOOL_LABELS} from './config.js';
const cf={M:1,mM:1e-3,uM:1e-6,nM:1e-9};const vf={L:1,mL:1e-3,uL:1e-6,nL:1e-9};const mf={g:1,mg:1e-3,ug:1e-6};
const pos=(v,n)=>{v=Number(v);if(!Number.isFinite(v)||v<=0)throw new Error(`${n} must be greater than zero.`);return v};
const nonneg=(v,n)=>{v=Number(v);if(!Number.isFinite(v)||v<0)throw new Error(`${n} cannot be negative.`);return v};
const convert=(v,from,to,map)=>{if(!(from in map)||!(to in map))throw new Error('Incompatible units.');return Number(v)*map[from]/map[to]};
const fmt=n=>Number.isFinite(n)?Number(n.toPrecision(7)):NaN;
export function molarityToMass({concentration,concentrationUnit='mM',volume,volumeUnit='mL',mw,massUnit='mg'}){const c=pos(concentration,'Concentration')*cf[concentrationUnit];const V=pos(volume,'Volume')*vf[volumeUnit];const M=pos(mw,'Molecular weight');const grams=c*V*M;return {mass:{value:fmt(grams/mf[massUnit]),unit:massUnit},moles:{value:fmt(c*V),unit:'mol'}}}
export function massToMolarity({mass,massUnit='mg',volume,volumeUnit='mL',mw,concentrationUnit='mM'}){const g=pos(mass,'Mass')*mf[massUnit];const V=pos(volume,'Volume')*vf[volumeUnit];const M=pos(mw,'Molecular weight');const molarity=g/M/V;return {concentration:{value:fmt(molarity/cf[concentrationUnit]),unit:concentrationUnit}}}
export function dilution({c1,c1Unit='mM',c2,c2Unit='mM',v2,v2Unit='mL',outUnit='mL'}){const C1=pos(c1,'Stock concentration')*cf[c1Unit],C2=pos(c2,'Target concentration')*cf[c2Unit],V2=pos(v2,'Final volume')*vf[v2Unit];if(C2>C1)throw new Error('Target concentration cannot exceed stock concentration.');const V1=C2*V2/C1;return {stockVolume:{value:fmt(V1/vf[outUnit]),unit:outUnit},diluentVolume:{value:fmt((V2-V1)/vf[outUnit]),unit:outUnit}}}
export function cellSeeding({cellsPerWell,wells,suspensionCellsPerMl,volumePerWellUl,overage=10}){const cpw=pos(cellsPerWell,'Cells per well'),n=pos(wells,'Wells'),conc=pos(suspensionCellsPerMl,'Suspension concentration'),vpw=pos(volumePerWellUl,'Volume per well'),extra=nonneg(overage,'Overage')/100;const finalMl=n*vpw/1000*(1+extra);const cells=cpw*n*(1+extra);const suspensionMl=cells/conc;if(suspensionMl>finalMl)throw new Error('Required cell-suspension volume exceeds final mixture volume. Concentrate the cells or increase final volume.');return {totalCells:{value:fmt(cells),unit:'cells'},cellSuspension:{value:fmt(suspensionMl),unit:'mL'},medium:{value:fmt(finalMl-suspensionMl),unit:'mL'},finalVolume:{value:fmt(finalMl),unit:'mL'}}}
export function rnaCdna({stock,target,volume}){const s=pos(stock,'RNA stock concentration'),t=pos(target,'Target concentration'),v=pos(volume,'Reaction volume');if(t>s)throw new Error('Target RNA concentration cannot exceed stock concentration.');const stockVol=t*v/s;return {rna:{value:fmt(stockVol),unit:'uL'},water:{value:fmt(v-stockVol),unit:'uL'}}}
export function theoreticalCapacity({electrons,mw}){return {capacity:{value:fmt(pos(electrons,'Electrons')*96485.33212/(3.6*pos(mw,'Molar mass'))),unit:'mAh/g'}}}
export function cRate({capacity,rate}){return {current:{value:fmt(pos(capacity,'Capacity')*pos(rate,'C-rate')),unit:'mA'}}}
export function currentDensity({current,area}){return {currentDensity:{value:fmt(pos(current,'Current')/pos(area,'Area')),unit:'mA/cm²'}}}
export function faraday({charge,electrons=1}){return {moles:{value:fmt(pos(charge,'Charge')/(pos(electrons,'Electrons')*96485.33212)),unit:'mol'}}}
export function stoichiometry({baseMmol,equivalents,mw}){const mmol=pos(baseMmol,'Base amount')*pos(equivalents,'Equivalents');const out={amount:{value:fmt(mmol),unit:'mmol'}};if(Number(mw)>0)out.mass={value:fmt(mmol*Number(mw)),unit:'mg'};return out}
export function percentYield({actual,theoretical}){return {yield:{value:fmt(pos(actual,'Actual yield')/pos(theoretical,'Theoretical yield')*100),unit:'%'}}}
export function heatingRamp({start,end,rate,dwell=0}){const s=Number(start),e=Number(end),r=pos(rate,'Ramp rate');if(!Number.isFinite(s)||!Number.isFinite(e)||e===s)throw new Error('Enter different start and end temperatures.');return {rampTime:{value:fmt(Math.abs(e-s)/r),unit:'min'},totalProgram:{value:fmt(Math.abs(e-s)/r+nonneg(dwell,'Dwell')),unit:'min'}}}
export function rcfToRpm({rcf,radius}){return {rpm:{value:fmt(Math.sqrt(pos(rcf,'RCF')/(1.118e-5*pos(radius,'Rotor radius')))),unit:'rpm'}}}
export function rpmToRcf({rpm,radius}){return {rcf:{value:fmt(1.118e-5*pos(radius,'Rotor radius')*pos(rpm,'RPM')**2),unit:'×g'}}}
export function encapsulation({initial,free,recovered,startingSolids}){const i=pos(initial,'Initial payload'),f=nonneg(free,'Free payload');if(f>i)throw new Error('Free payload cannot exceed initial payload.');const enc=i-f,out={ee:{value:fmt(enc/i*100),unit:'%'}};if(Number(recovered)>0)out.loading={value:fmt(enc/Number(recovered)*100),unit:'%'};if(Number(startingSolids)>0&&Number(recovered)>0)out.recovery={value:fmt(Number(recovered)/Number(startingSolids)*100),unit:'%'};return out}
export function beerLambert({absorbance,epsilon,path=1}){return {concentration:{value:fmt(nonneg(absorbance,'Absorbance')/(pos(epsilon,'Extinction coefficient')*pos(path,'Path length'))),unit:'M'}}}
export function odEstimate({od,volume=1,coefficient=8e8}){return {cells:{value:fmt(nonneg(od,'OD600')*pos(volume,'Volume')*pos(coefficient,'Calibration coefficient')),unit:'cells'}}}
export function reagentMass({mw,concentration,unit='mM',volume}){return molarityToMass({mw,concentration,concentrationUnit:unit,volume,volumeUnit:'mL',massUnit:'g'})}
export function composition({massA,mwA,massB,mwB}){const a=nonneg(massA,'Mass A'),b=nonneg(massB,'Mass B');if(a+b<=0)throw new Error('Total mass must be greater than zero.');const out={wtA:{value:fmt(a/(a+b)*100),unit:'wt%'},wtB:{value:fmt(b/(a+b)*100),unit:'wt%'}};if(Number(mwA)>0&&Number(mwB)>0){const na=a/Number(mwA),nb=b/Number(mwB);out.atA={value:fmt(na/(na+nb)*100),unit:'at%'};out.atB={value:fmt(nb/(na+nb)*100),unit:'at%'};}return out}
export function formulation({componentA,componentB}){const a=pos(componentA,'Component A'),b=pos(componentB,'Component B');return {ratio:`${fmt(a/b)} : 1`,fractionA:{value:fmt(a/(a+b)*100),unit:'%'},fractionB:{value:fmt(b/(a+b)*100),unit:'%'}}}

function outputText(o){return Object.entries(o).map(([k,v])=>typeof v==='string'?`${label(k)}: ${v}`:`${label(k)}: ${v.value} ${v.unit}`).join(' · ')}
const label=s=>s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
function field(id,labelText,unit='',value=''){return `<label>${labelText}<div class="input-unit"><input id="${id}" type="number" step="any" value="${value}">${unit?`<span>${unit}</span>`:''}</div></label>`}
function select(id,labelText,options){return `<label>${labelText}<select id="${id}">${options.map(o=>`<option>${o}</option>`).join('')}</select></label>`}
function val(container,id){return container.querySelector('#'+id)?.value}
function emit(container,id,inputs,outputs,warnings=[]){const detail={toolId:id,toolVersion:'1.0.0',inputs,outputs,warnings,createdAt:new Date().toISOString()};container.dispatchEvent(new CustomEvent('noor-tool-result',{bubbles:true,detail}));const out=container.querySelector('.tool-output');out.textContent=outputText(outputs);container.querySelector('.attach-calc')?.removeAttribute('disabled');container.dataset.lastResult=JSON.stringify(detail)}
function run(container,fn){try{fn()}catch(e){container.querySelector('.tool-output').textContent=e.message;}}
function shell(id,body,note=''){return `<div class="tool-title"><div><span class="goose">Silly Goose</span><h3>${TOOL_LABELS[id]}</h3></div><button class="close-tool" aria-label="Close">×</button></div>${note?`<p class="tool-note">${note}</p>`:''}${body}<div class="tool-actions"><button class="attach-calc" disabled>Attach calculation</button></div><output class="tool-output">—</output>`}
export function renderTool(container,id){container.classList.remove('hidden');let html='',setup=()=>{};
 if(id==='molarity'){html=shell(id,`<div class="calc-row">${field('conc','Concentration','mM')}${field('vol','Volume','mL')}${field('mw','Molecular weight','g/mol')}</div><button class="calc">Calculate mass</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{concentration:val(container,'conc'),volume:val(container,'vol'),mw:val(container,'mw')},molarityToMass({concentration:val(container,'conc'),volume:val(container,'vol'),mw:val(container,'mw')})))}
 else if(id==='dilution'){html=shell(id,`<div class="calc-row">${field('c1','Stock C1','mM')}${field('c2','Target C2','mM')}${field('v2','Final V2','mL')}</div><button class="calc">Calculate</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{c1:val(container,'c1'),c2:val(container,'c2'),v2:val(container,'v2')},dilution({c1:val(container,'c1'),c2:val(container,'c2'),v2:val(container,'v2')})))}
 else if(id==='seeding'){html=shell(id,`<div class="calc-row">${field('cpw','Cells / well')}${field('wells','Wells')}${field('cellconc','Suspension','cells/mL')}${field('vpw','Volume / well','uL','100')}${field('over','Overage','%','10')}</div><button class="calc">Calculate seeding mix</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},cellSeeding({cellsPerWell:val(container,'cpw'),wells:val(container,'wells'),suspensionCellsPerMl:val(container,'cellconc'),volumePerWellUl:val(container,'vpw'),overage:val(container,'over')})))}
 else if(id==='rna'){html=shell(id,`<div class="calc-row">${field('stock','RNA stock','ng/uL')}${field('target','Target','ng/uL')}${field('rxnvol','Reaction volume','uL')}</div><button class="calc">Calculate dilution</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},rnaCdna({stock:val(container,'stock'),target:val(container,'target'),volume:val(container,'rxnvol')})))}
 else if(id==='stoich'){html=shell(id,`<div class="calc-row">${field('base','Limiting reagent','mmol')}${field('eq','Equivalents','','1')}${field('smw','MW (optional)','g/mol')}</div><button class="calc">Calculate reagent amount</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},stoichiometry({baseMmol:val(container,'base'),equivalents:val(container,'eq'),mw:val(container,'smw')})))}
 else if(id==='yield'){html=shell(id,`<div class="calc-row">${field('actual','Actual yield')}${field('theory','Theoretical yield')}</div><button class="calc">Calculate % yield</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},percentYield({actual:val(container,'actual'),theoretical:val(container,'theory')})))}
 else if(id==='rotavap'){html=shell(id,`${select('solvent','Solvent',SOLVENTS.map(s=>s.name))}<div class="solvent-card"></div>`,`Vacuum values are BÜCHI reference values for a 40 °C solvent boiling point. Treat them as equipment guidance, not a substitute for your instrument manual/SDS.`);setup=()=>{const update=()=>{const s=SOLVENTS.find(x=>x.name===val(container,'solvent'));container.querySelector('.solvent-card').innerHTML=`<b>${s.name}</b><span>${s.formula}</span><div>Normal bp: <strong>${s.bp} °C</strong></div><div>Density: <strong>${s.density} g/cm³</strong></div><div>40 °C boiling vacuum: <strong>${s.vacuum40} mbar</strong></div>`;emit(container,id,{solvent:s.name},{boilingPoint:{value:s.bp,unit:'°C'},vacuum40:{value:s.vacuum40,unit:'mbar'}})};container.querySelector('#solvent').onchange=update;update()}}
 else if(id==='capacity'){html=shell(id,`<div class="calc-row">${field('ne','Electrons n','','1')}${field('cmw','Molar mass','g/mol')}</div><button class="calc">Calculate capacity</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},theoreticalCapacity({electrons:val(container,'ne'),mw:val(container,'cmw')})))}
 else if(id==='crate'){html=shell(id,`<div class="calc-row">${field('cap','Capacity','mAh')}${field('rate','C-rate','C')}</div><button class="calc">Calculate current</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},cRate({capacity:val(container,'cap'),rate:val(container,'rate')})))}
 else if(id==='currentdensity'){html=shell(id,`<div class="calc-row">${field('curr','Current','mA')}${field('area','Active area','cm²')}</div><button class="calc">Calculate</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},currentDensity({current:val(container,'curr'),area:val(container,'area')})))}
 else if(id==='faraday'){html=shell(id,`<div class="calc-row">${field('charge','Charge','C')}${field('fe','Electrons n','','1')}</div><button class="calc">Calculate moles</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},faraday({charge:val(container,'charge'),electrons:val(container,'fe')})))}
 else if(id==='heating'){html=shell(id,`<div class="calc-row">${field('ts','Start','°C')}${field('te','End','°C')}${field('hr','Ramp','°C/min')}${field('dwell','Dwell','min','0')}</div><button class="calc">Calculate program</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},heatingRamp({start:val(container,'ts'),end:val(container,'te'),rate:val(container,'hr'),dwell:val(container,'dwell')})))}
 else if(id==='rcf'){html=shell(id,`<div class="calc-row">${field('rcf','RCF','×g')}${field('rad','Radius','cm')}</div><button class="calc">RCF → RPM</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},rcfToRpm({rcf:val(container,'rcf'),radius:val(container,'rad')})))}
 else if(id==='ee'){html=shell(id,`<div class="calc-row">${field('initial','Initial payload')}${field('free','Free payload')}${field('recovered','Recovered particles')}${field('solids','Starting solids')}</div><button class="calc">Calculate</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},encapsulation({initial:val(container,'initial'),free:val(container,'free'),recovered:val(container,'recovered'),startingSolids:val(container,'solids')})))}
 else if(id==='spectro'){html=shell(id,`<div class="calc-row">${field('abs','Absorbance A')}${field('eps','ε','M⁻¹cm⁻¹')}${field('path','Path length','cm','1')}</div><button class="calc">Beer–Lambert concentration</button><details><summary>OD600 estimate</summary><div class="calc-row">${field('od','OD600')}${field('odvol','Culture volume','mL','1')}${field('coeff','Cells/mL/OD','','800000000')}</div><button class="odcalc">Estimate</button></details>`,`OD600 conversion is an assumption. Replace the coefficient with your organism/instrument calibration.`);setup=()=>{container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},beerLambert({absorbance:val(container,'abs'),epsilon:val(container,'eps'),path:val(container,'path')})));container.querySelector('.odcalc').onclick=()=>run(container,()=>emit(container,id,{},odEstimate({od:val(container,'od'),volume:val(container,'odvol'),coefficient:val(container,'coeff')})))}}
 else if(id==='buffer'){html=shell(id,`<div class="calc-row">${field('bmw','Molecular weight','g/mol')}${field('bc','Concentration','mM')}${field('bv','Final volume','mL')}</div><button class="calc">Calculate reagent mass</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},reagentMass({mw:val(container,'bmw'),concentration:val(container,'bc'),volume:val(container,'bv')})))}
 else if(id==='composition'){html=shell(id,`<div class="calc-row">${field('ma','Mass A','g')}${field('mwa','MW A','g/mol')}${field('mb','Mass B','g')}${field('mwb','MW B','g/mol')}</div><button class="calc">Calculate composition</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},composition({massA:val(container,'ma'),mwA:val(container,'mwa'),massB:val(container,'mb'),mwB:val(container,'mwb')})))}
 else if(id==='formulation'){html=shell(id,`<div class="calc-row">${field('fa','Component A')}${field('fb','Component B')}</div><button class="calc">Calculate ratio</button>`);setup=()=>container.querySelector('.calc').onclick=()=>run(container,()=>emit(container,id,{},formulation({componentA:val(container,'fa'),componentB:val(container,'fb')})))}
 else if(id==='pcr'){html=shell(id,`<div class="calc-row">${field('prxn','Reactions','','10')}${field('pvol','Volume / reaction','uL','20')}${field('pover','Overage','%','10')}</div><div id="pcrRows"></div><button class="add-reagent" type="button">+ Reagent</button><button class="calc">Calculate master mix</button>`);setup=()=>setupPcr(container,id)}
 else if(id==='plate96'){html=shell(id,`<div class="plate-controls"><input id="plateDefault" placeholder="Label selected wells"><button class="fill-selected">Fill selected</button><button class="clear-plate">Clear</button><button class="export-plate">Export CSV</button></div><div class="plate96"></div>`,`Click wells to select them. Labels stay local with your notebook.`);setup=()=>setupPlate(container,id)}
 else if(id==='timer'){html=shell(id,`<div class="calc-row">${field('minutes','Duration','min','10')}</div><button class="start-timer">Start</button><button class="stop-timer">Stop</button><div class="timer-display">00:00</div>`);setup=()=>setupTimer(container,id)}
 else html=shell(id,'<p>Tool unavailable.</p>');
 container.innerHTML=html;container.querySelector('.close-tool').onclick=()=>container.classList.add('hidden');setup();container.querySelector('.attach-calc')?.addEventListener('click',()=>{if(container.dataset.lastResult)container.dispatchEvent(new CustomEvent('noor-attach-calculation',{bubbles:true,detail:JSON.parse(container.dataset.lastResult)}))});
}
function setupPcr(c,id){const rows=c.querySelector('#pcrRows');const add=(name='Reagent',stock=10,final=1)=>{const d=document.createElement('div');d.className='pcr-row';d.innerHTML=`<input class="rname" value="${name}"><input class="rstock" type="number" step="any" value="${stock}" placeholder="stock"><input class="rfinal" type="number" step="any" value="${final}" placeholder="final"><button type="button">×</button>`;d.querySelector('button').onclick=()=>d.remove();rows.appendChild(d)};['Primer F','Primer R','dNTP'].forEach((n,i)=>add(n,i<2?10:10,i<2?.5:.2));c.querySelector('.add-reagent').onclick=()=>add();c.querySelector('.calc').onclick=()=>run(c,()=>{const n=pos(val(c,'prxn'),'Reactions'),rv=pos(val(c,'pvol'),'Reaction volume'),over=nonneg(val(c,'pover'),'Overage')/100,totalRxn=n*(1+over);let usedPer=0;const reagents=[...rows.children].map(r=>{const name=r.querySelector('.rname').value,stock=pos(r.querySelector('.rstock').value,`${name} stock`),final=nonneg(r.querySelector('.rfinal').value,`${name} final`);const per=final/stock*rv;usedPer+=per;return {name,perReaction:fmt(per),total:fmt(per*totalRxn)}});if(usedPer>rv)throw new Error('Reagent volumes exceed reaction volume.');const outputs={totalReactions:{value:fmt(totalRxn),unit:'rxn'},masterMix:{value:fmt(rv*totalRxn),unit:'uL'},water:{value:fmt((rv-usedPer)*totalRxn),unit:'uL'}};emit(c,id,{reagents},outputs);c.querySelector('.tool-output').textContent=outputText(outputs)+' · '+reagents.map(r=>`${r.name}: ${r.total} uL`).join(' · ')}) )}
function setupPlate(c,id){const grid=c.querySelector('.plate96');const selected=new Set();const data={};grid.innerHTML='<span></span>'+Array.from({length:12},(_,i)=>`<b>${i+1}</b>`).join('')+Array.from({length:8},(_,ri)=>`<b>${String.fromCharCode(65+ri)}</b>`+Array.from({length:12},(_,ci)=>{const w=String.fromCharCode(65+ri)+(ci+1);return `<button data-well="${w}" title="${w}">${w}</button>`}).join('')).join('');grid.querySelectorAll('[data-well]').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');b.classList.contains('selected')?selected.add(b.dataset.well):selected.delete(b.dataset.well)});c.querySelector('.fill-selected').onclick=()=>{const label=c.querySelector('#plateDefault').value;selected.forEach(w=>{data[w]=label;const b=grid.querySelector(`[data-well="${w}"]`);b.textContent=label||w;b.classList.remove('selected')});selected.clear();emit(c,id,{format:96},{labeledWells:{value:Object.keys(data).length,unit:'wells'}});c.dataset.plate=JSON.stringify(data)};c.querySelector('.clear-plate').onclick=()=>{Object.keys(data).forEach(k=>delete data[k]);grid.querySelectorAll('[data-well]').forEach(b=>{b.textContent=b.dataset.well;b.classList.remove('selected')});selected.clear()};c.querySelector('.export-plate').onclick=()=>{let csv='Well,Label\n'+Array.from({length:96},(_,i)=>{const row=String.fromCharCode(65+Math.floor(i/12)),well=row+(i%12+1);return `${well},"${(data[well]||'').replaceAll('"','""')}"`}).join('\n');downloadText('noor-plate-96.csv',csv,'text/csv')}}
function setupTimer(c,id){let handle;const display=c.querySelector('.timer-display');const key='noor.timer.active';const render=()=>{const end=Number(localStorage.getItem(key)||0);if(!end){display.textContent='00:00';return}const left=Math.max(0,Math.ceil((end-Date.now())/1000));display.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left===0){clearInterval(handle);localStorage.removeItem(key)}};c.querySelector('.start-timer').onclick=()=>{const mins=pos(val(c,'minutes'),'Duration');localStorage.setItem(key,String(Date.now()+mins*60000));clearInterval(handle);handle=setInterval(render,250);render();emit(c,id,{minutes:mins},{endsAt:new Date(Date.now()+mins*60000).toISOString()})};c.querySelector('.stop-timer').onclick=()=>{localStorage.removeItem(key);clearInterval(handle);render()};handle=setInterval(render,1000);render()}
function downloadText(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export {downloadText,convert,cf,vf,mf};
